plugins {
    id 'com.android.application'
}

android {
    namespace 'pw.hexed.fingerprint'

    compileSdk 36
    
    defaultConfig {
        applicationId 'pw.hexed.fingerprint'
        minSdk 31
        targetSdk 36
        versionCode 201000
        versionName '2.0.1'
    }
    
    buildTypes {
        release {
            minifyEnabled true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}

dependencies {
    implementation 'androidx.biometric:biometric:1.1.0'
}
