name: Build
run-name: Build @ ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: Changelog [base64]
        required: true
      publish:
        type: boolean
        default: true
        description: Publish

env:
  token: ${{ secrets.GH_TOKEN || github.token }}
  filename: termux-fingerprint
  owner: flameshikari

concurrency: ${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 20

    - name: Extract Values
      run: |
        cat << EOF >> $GITHUB_ENV
        version=$(grep versionName app/build.gradle | awk -F"'" '{print $2}')
        package_name=$(grep applicationId app/build.gradle | awk -F"'" '{print $2}')
        EOF

    - name: Create changelog
      run: |
        whatsnew="whatsnew"
        changelog="$whatsnew/whatsnew-en-US"
        mkdir -pv "$whatsnew"
        echo "${{ inputs.changelog }}" | base64 -d | tee "$changelog"
        cat << EOF >> $GITHUB_ENV
        whatsnew=$whatsnew
        changelog=$changelog
        EOF

    - name: Build AAB & APK
      run: |
        gradle assembleRelease
        gradle bundleRelease
        mv -v app/build/outputs/apk/release/*.apk .
        mv -v app/build/outputs/bundle/release/*.aab .

    - name: Sign AAB & APK
      uses: kevin-david/zipalign-sign-android-release@main
      id: sign
      with:
        alias: ${{ secrets.KEYSTORE_ALIAS }}
        keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        releaseDirectory: .

    - name: Rename AAB & APK
      env:
        f0: ${{ steps.sign.outputs.signedReleaseFile0 }}
        f1: ${{ steps.sign.outputs.signedReleaseFile1 }}
      run: |
        for signed in ${{ env.f0 }} ${{ env.f1 }}; do
          mv -v $signed ${{ env.filename }}.$(echo $signed | awk -F. '{if (NF>1) print $NF}')
        done

    - name: Upload signed AAB & APK in Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.filename }}
        path: |
          ${{ env.filename }}.aab
          ${{ env.filename }}.apk
        retention-days: 7

    - name: Create a GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.filename }}.apk
        name: ${{ env.version }}
        tag_name: ${{ env.version }}
        token: ${{ env.token }}
        body_path: ${{ env.changelog }}
      if: |
        github.repository_owner == ${{ env.owner }} &&
        inputs.publish == true

    - name: Upload AAB to Google Play 
      uses: r0adkll/upload-google-play@v1
      with:
        releaseFiles: ${{ env.filename }}.aab
        packageName: ${{ env.package_name }}
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
        mappingFile: app/build/outputs/mapping/release/mapping.txt
        whatsNewDirectory: ${{ env.whatsnew }}
        inAppUpdatePriority: 5
      if: |
        github.repository_owner == ${{ env.owner }} &&
        inputs.publish == true
