name: Build
run-name: Build @ ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: 1.0.0

env:
  filename: fingerprint
  version: ${{ inputs.version }}

concurrency: ${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 20

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.8

    - name: Build AAB & APK
      run: |
        gradle assembleRelease
        gradle bundleRelease
        mv -v app/build/outputs/apk/release/*.apk .
        mv -v app/build/outputs/bundle/release/*.aab .

    - name: Sign AAB & APK
      uses: kevin-david/zipalign-sign-android-release@main
      id: sign_step
      with:
        alias: ${{ secrets.KEYSTORE_ALIAS }}
        keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        releaseDirectory: .

    - name: Rename AAB & APK
      env:
        f0: ${{ steps.sign_step.outputs.signedReleaseFile0 }}
        f1: ${{ steps.sign_step.outputs.signedReleaseFile1 }}
      run: |
        for signed in ${{ env.f0 }} ${{ env.f1 }}; do
          mv -v $signed ${{ env.filename }}.$(echo $signed | awk -F. '{if (NF>1) print $NF}')
        done

    - name: Upload signed AAB & APK in Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.filename }}
        path: |
          ${{ env.filename }}.aab
          ${{ env.filename }}.apk
        retention-days: 7

    - name: Create a GitHub release
      uses: softprops/action-gh-release@v2
      if: github.repository_owner == 'flameshikari/termux-fingerprint'
      with:
        files: ${{ env.filename }}.apk
        name: ${{ env.version }}
        tag_name: ${{ env.version }}
        token: ${{ secrets.GH_TOKEN }}
